name: Testing stuff

on:
  push:
    branches:
      - main

env:
  COMMITS_CONTAINS_SKIP: ${{ contains(join(github.event.commits.*.message, ' '), '#skip') }}

jobs:
  job2:
    runs-on: ubuntu-20.04
    steps:
      - name: Print contents of COMMITS_CONTAINS_SKIP
        run: |
          echo ${{ env.COMMITS_CONTAINS_SKIP }}
      - name: Check if commit message contains skip
        if: ${{ env.COMMITS_CONTAINS_SKIP == 'true' }}
        run: echo "Commit message contains skip"
      - name: Check if commit message doesnt contains skip
        if: ${{ env.COMMITS_CONTAINS_SKIP == 'false' }}
        run: echo "Commit message does not contain skip"